export const ERROR_CODES = {
  // Auth Errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_UNAUTHORIZED: 'AUTH_004',
  AUTH_FORBIDDEN: 'AUTH_005',
  AUTH_OTP_INVALID: 'AUTH_006',
  AUTH_OTP_EXPIRED: 'AUTH_007',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_008',
  AUTH_ACCOUNT_BLOCKED: 'AUTH_009',

  // User Errors
  USER_NOT_FOUND: 'USR_001',
  USER_ALREADY_EXISTS: 'USR_002',
  USER_PHONE_EXISTS: 'USR_003',
  USER_EMAIL_EXISTS: 'USR_004',

  // Driver Errors
  DRIVER_NOT_FOUND: 'DRV_001',
  DRIVER_NOT_AVAILABLE: 'DRV_002',
  DRIVER_ALREADY_EXISTS: 'DRV_003',
  DRIVER_KYC_PENDING: 'DRV_004',
  DRIVER_KYC_REJECTED: 'DRV_005',
  DRIVER_VEHICLE_NOT_FOUND: 'DRV_006',
  DRIVER_ALREADY_ON_RIDE: 'DRV_007',

  // Ride Errors
  RIDE_NOT_FOUND: 'RID_001',
  RIDE_CANNOT_CANCEL: 'RID_002',
  RIDE_ALREADY_ASSIGNED: 'RID_003',
  RIDE_NO_DRIVERS_AVAILABLE: 'RID_004',
  RIDE_INVALID_STATUS: 'RID_005',
  RIDE_TOO_FAR: 'RID_006',
  RIDE_CANCELLATION_NOT_ALLOWED: 'RID_007',

  // Payment Errors
  PAYMENT_FAILED: 'PAY_001',
  PAYMENT_INSUFFICIENT_BALANCE: 'PAY_002',
  PAYMENT_INVALID: 'PAY_003',
  PAYMENT_VERIFICATION_FAILED: 'PAY_004',
  PAYMENT_REFUND_FAILED: 'PAY_005',

  // Wallet Errors
  WALLET_INSUFFICIENT_BALANCE: 'WAL_001',
  WALLET_NOT_FOUND: 'WAL_002',
  WALLET_TRANSACTION_FAILED: 'WAL_003',

  // Coupon Errors
  COUPON_INVALID: 'CPN_001',
  COUPON_EXPIRED: 'CPN_002',
  COUPON_USAGE_EXCEEDED: 'CPN_003',
  COUPON_NOT_APPLICABLE: 'CPN_004',

  // Validation Errors
  VALIDATION_ERROR: 'VAL_001',
  INVALID_INPUT: 'VAL_002',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RAT_001',

  // General
  INTERNAL_SERVER_ERROR: 'INT_001',
  SERVICE_UNAVAILABLE: 'INT_002',
  NOT_FOUND: 'INT_003',
  BAD_REQUEST: 'INT_004',
  CONFLICT: 'INT_005',

  // KYC
  KYC_ALREADY_SUBMITTED: 'KYC_001',
  KYC_DOCUMENT_INVALID: 'KYC_002',
  KYC_NOT_VERIFIED: 'KYC_003',

  // Notification
  NOTIFICATION_FAILED: 'NOT_001',
  FCM_TOKEN_INVALID: 'NOT_002',
} as const;

export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid credentials provided',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Access token has expired',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Invalid access token',
  [ERROR_CODES.AUTH_UNAUTHORIZED]: 'Authentication required',
  [ERROR_CODES.AUTH_FORBIDDEN]: 'You do not have permission to perform this action',
  [ERROR_CODES.AUTH_OTP_INVALID]: 'Invalid OTP',
  [ERROR_CODES.AUTH_OTP_EXPIRED]: 'OTP has expired',
  [ERROR_CODES.AUTH_REFRESH_TOKEN_INVALID]: 'Invalid refresh token',
  [ERROR_CODES.AUTH_ACCOUNT_BLOCKED]: 'Account has been blocked',
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists',
  [ERROR_CODES.DRIVER_NOT_FOUND]: 'Driver not found',
  [ERROR_CODES.DRIVER_NOT_AVAILABLE]: 'No drivers available nearby',
  [ERROR_CODES.RIDE_NOT_FOUND]: 'Ride not found',
  [ERROR_CODES.RIDE_CANNOT_CANCEL]: 'Ride cannot be cancelled at this stage',
  [ERROR_CODES.RIDE_NO_DRIVERS_AVAILABLE]: 'No drivers available',
  [ERROR_CODES.PAYMENT_FAILED]: 'Payment processing failed',
  [ERROR_CODES.PAYMENT_INSUFFICIENT_BALANCE]: 'Insufficient wallet balance',
  [ERROR_CODES.PAYMENT_VERIFICATION_FAILED]: 'Payment verification failed',
  [ERROR_CODES.WALLET_INSUFFICIENT_BALANCE]: 'Insufficient balance in wallet',
  [ERROR_CODES.COUPON_INVALID]: 'Invalid coupon code',
  [ERROR_CODES.COUPON_EXPIRED]: 'Coupon has expired',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Too many requests. Please try again later',
  [ERROR_CODES.KYC_NOT_VERIFIED]: 'KYC verification is pending',
  [ERROR_CODES.NOTIFICATION_FAILED]: 'Failed to send notification',
};
