apiVersion: v1
kind: Secret
metadata:
  name: ride-secrets
  namespace: ride-hailing
type: Opaque
data:
  DB_USERNAME: cmlkZV91c2Vy
  DB_PASSWORD: cmlkZV9wYXNzd29yZA==
  JWT_ACCESS_SECRET: eW91ci1qd3QtYWNjZXNzLXNlY3JldC1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  JWT_REFRESH_SECRET: eW91ci1qd3QtcmVmcmVzaC1zZWNyZXQtY2hhbmdlLWluLXByb2R1Y3Rpb24=
  RAZORPAY_KEY_ID: cnpwX2xpdmVfeHh4eHh4eHh4eHh4
  RAZORPAY_KEY_SECRET: eHh4eHh4eHh4eHh4eHh4eHh4eA==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: ride-hailing
type: Opaque
data:
  POSTGRES_USER: cmlkZV91c2Vy
  POSTGRES_PASSWORD: cmlkZV9wYXNzd29yZA==
